
backend_test:
  image: "docker:stable"
  services:
    - docker:dind
  before_script:
    - date
    - uname -a
    - ls -l
    - docker build -t backend ./website_backend
  script:
    - docker run -v ${PWD}/website_backend/app:/app -w /app -d -p 80:80 backend python test.py

backend_deploy:
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /deploy/i
  image: "registry.gitlab.com/cmibarnwell/idb-project-swe"
  before_script:
    - date
    - uname -a
    - ls -l
    - echo "$USER_PASS" > idb-backend.pem
    - chmod 400 idb-backend.pem
  script:
    - tar cpf - ./website_backend | ssh -o StrictHostKeyChecking=no -v -i "idb-backend.pem" ec2-user@ec2-34-218-254-20.us-west-2.compute.amazonaws.com "tar xpf - -C /home/ec2-user"
    - ssh -v -o StrictHostKeyChecking=no -i "idb-backend.pem" ec2-user@ec2-34-218-254-20.us-west-2.compute.amazonaws.com 'cd /home/ec2-user/website_backend; docker container stop $(docker ps -q); docker container kill $(docker ps -q); docker system prune; docker build -t backend .; docker run -d -v /home/ec2-user/website_backend/app:/app -w /app -p 80:80 -t backend' 
#docker exec $(docker ps --format "{{.Names}}") python test.py;'
