variables:
  S3_BUCKET_NAME: "www.ourplaceholderwebsite.me"
deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp website_frontend/ s3://$S3_BUCKET_NAME/ --recursive --include "*"