backend_test:
  image: "docker:stable"
  services:
    - docker:dind
  before_script:
    - date
    - uname -a
    - ls -l
    - docker build -t backend ./website_backend
  script:
    - docker run -i -v ${PWD}/website_backend/app:/app -w /app -p 80:80 backend /bin/bash -c "bash init.sh &; newman run postman_tests.json -x"

backend_deploy:
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /deploy/i
  image: "registry.gitlab.com/cmibarnwell/idb-project-swe"
  before_script:
    - date
    - uname -a
    - ls -l
    - echo "$USER_PASS" > idb-backend.pem
    - chmod 400 idb-backend.pem
  script:
    - tar cpf - ./website_backend | ssh -o StrictHostKeyChecking=no -v -i "idb-backend.pem" ec2-user@ec2-34-218-254-20.us-west-2.compute.amazonaws.com "tar xpf - -C /home/ec2-user"
    - ssh -v -o StrictHostKeyChecking=no -i "idb-backend.pem" ec2-user@ec2-34-218-254-20.us-west-2.compute.amazonaws.com '/home/ec2-user/website_backend/deploy.sh'

frontend_test:
  # currently runs Mocha tests only using generic "node" container
  image: "node:9.6.1"
  script:
    - cd website_frontend
    - ls -al
    - npm update && npm install -g mocha
    - mocha test

frontend_deploy:
  # pushes this code to frontend dev server, accessible at ourplaceholderwebsite.me
  before_script:
    - echo "$FRONTEND_KEY" > kytFrontEndKey.pem
    - chmod 400 kytFrontEndKey.pem
  script:
    - ssh -v -o StrictHostKeyChecking=no -i "kytFrontEndKey.pem" ubuntu@18.191.169.207 "./update.sh"
