backend_test:
  image: "registry.gitlab.com/cmibarnwell/idb-project-swe"
  before_script:
    - date
    - uname -a
    - ls -l
    - docker build -t backend ./website_backend
    - docker run -v ./website_backend/app:/app -w /app -p 80:80 backend
  script:
    - docker exec $(docker ps --format "{{.Names}}") python website_backend/app/test.py

backend_deploy:
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /deploy/i
  image: "registry.gitlab.com/cmibarnwell/idb-project-swe"
  before_script:
    - date
    - uname -a
    - ls -l
  script:
    #- echo "$USER_PASS"
    # note: revise this so it creates a new docker container
    # to run the tests in instead of the main one
    - echo "$USER_PASS" > idb-backend.pem
    - chmod 400 idb-backend.pem
    - echo "--- tar over ssh ---"
    - tar cpf - ./website_backend | ssh -o StrictHostKeyChecking=no -v -i "idb-backend.pem" ec2-user@ec2-34-218-254-20.us-west-2.compute.amazonaws.com "tar xpf - -C /home/ec2-user"
    - echo "--- ssh ---"
    - ssh -v -o StrictHostKeyChecking=no -i "idb-backend.pem" ec2-user@ec2-34-218-254-20.us-west-2.compute.amazonaws.com 'cd /home/ec2-user/website_backend; docker container stop $(docker ps -q); docker container kill $(docker ps -q); docker system prune; build -t backend .; docker run -v /home/ec2-user/website_backend/app:/app -w /app -d --restart=always -p 80:80 -t backend; docker exec $(docker ps --format "{{.Names}}") python test.py;'