variables:
  S3_BUCKET_NAME: "www.knowyourtreatment.com"
deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp placeholderWebsite/ s3://$S3_BUCKET_NAME/ --recursive --include "*"