backend_test:
  image: "registry.gitlab.com/cmibarnwell/idb-project-swe:latest"
  before_script:
    - date
    - uname -a
    - ls -l
  script:
    - python website_backend/app/test.py

backend_deploy:
  only:
    - deploy
  image: "registry.gitlab.com/cmibarnwell/idb-project-swe:latest"
  before_script:
    - date
    - uname -a
    - ls -l
  script:
    - echo "$BE_EC2_PASS"
    - echo "$BE_EC2_PASS" > idb-backend.pem
    - chmod 400 idb-backend.pem
    - scp -v -o StrictHostKeyChecking=no -i "idb-backend.pem" -r website_backend/ ubuntu@ec2-34-238-244-3.compute-1.amazonaws.com:/var/www
    - ssh -v -o StrictHostKeyChecking=no -i "idb-backend.pem" ubuntu@ec2-34-238-244-3.compute-1.amazonaws.com
    - sudo apt update
    - cd /var/www/website_backend
    - sudo docker build -t backend .
    - sudo docker run -it -v /var/www/website_backend/app:/app -w /app -p 8080 backend python test.py
